### ISSUE TITLE
Implement persistent app settings

### ISSUE THREAD

**Issue by nateswart** [LunchboxDevTools/lunchbox#11]
Implement an app settings cache, so we can track certain things between app launches (like whether or not the VM needs to be re-provisioned). 

I'm thinking we should use this: http://electron.atom.io/docs/v0.35.0/api/app/#app-getpath-name

Specifically using the `appData` or `userData` location.

**Comment by yuriybabenko** [comment]
I've added functionality to create/write a 'settings.json' in the user's data path. On OSX, this is in `~/Library/Application Support/Lunchbox`.

This is handled via a new `storage` module. Look at `loadSettings()` in `drupalvm.js` to see how the data is loaded, and the (commented-out) code at line 84 to see an example of writing to the file.
