### ISSUE TITLE
Capture required user input (sudo password)

### ISSUE THREAD

**Issue by nateswart** [LunchboxDevTools/lunchbox#17]
Some commands (spawned child processes) may require additional user input (sudo password) to continue. We should catch this and handle it through the UI.

For example, the vagrant-hostsupdater plugin requires a sudo password in order to edit the /etc/hosts file. If you run lunchbox via `npm start` you'll see it prompt for the password.

**Comment by yuriybabenko** [comment]
Added support in https://github.com/LunchboxDevTools/lunchbox/commit/88378047c46c9495b63e4ae929a96dc245c415cb. 

Dialogs now have a text input & submit button at the bottom. These become enabled when `dialog.setChildProcess()` is called. On click of the submit button, any input in the textfield is passed to the child process. When the process' 'close' event fires, the input elements are disabled again.
