### ISSUE TITLE
Dependency check: Ensure ansible-galaxy install has been run

### ISSUE THREAD

**Issue by nateswart** [LunchboxDevTools/lunchbox#18]
DrupalVM will not successfully start until the ansible galaxy recipes have been downloaded. As part of the dependency check during Lunchbox startup we should also validate these recipes have been installed.

**Comment by geerlingguy** [comment]
In light of #19, this should only be run if `ansible` is present on the host. Otherwise it's run automatically as part of Drupal VM's setup inside the VM.

**Comment by yuriybabenko** [comment]
This is in place w/ in the latest PR. checkPrerequisites() checks for the presence of `ansible`, and if that's found, runs `ansible-galaxy list` to get the locally-available roles. The end result is compared against `https://raw.githubusercontent.com/geerlingguy/drupal-vm/master/provisioning/requirements.yml` and the delta is used to error out.

It would be better to check against a local version of `requirements.yml`, but I don't think we can reliably determine its location. Checking against remote file does run the risk of having that file change and break things. Additional downside is the requirement of an internet connection. 

Thoughts?

**Comment by nateswart** [comment]
@geerlingguy - Do you have any suggestions for validating the ansible provisioning requirements.yml has been processed?

@yuriybabenko - I just tested without ansible (and therefor without having run the galaxy recipes), and it's functioning properly, but reporting incorrectly. Here is a screenshot of what I see on a new machine with ansible *not* installed:

<img width="581" alt="screen shot 2015-12-09 at 8 43 21 am" src="https://cloud.githubusercontent.com/assets/839888/11686784/f0acdf5c-9e50-11e5-9cb4-0806120e70cf.png">

**Comment by geerlingguy** [comment]
@nateswart - Unfortunately, it's not super-simple right now, see:

  - https://github.com/ansible/ansible/issues/11266
  - https://github.com/ansible/galaxy-issues/issues/49

I'm hoping that the situation will be improved soon, but it could be some time. For now, a simple check of whether each role's directory exists in the configured ansible roles directory (as configured in `/etc/ansible/ansible.cfg`, `/etc/ansible/roles` by default) for each of the role names inside `requirements.yml` should suffice.

But hopefully in the future you could just run the `ansible-galaxy` command and it would do everything for you with idempotence.

**Comment by yuriybabenko** [comment]
@geerlingguy - Do you see any issues with checking the output of `ansible-galaxy list` vs. checking for role directories in those file paths? I'm hesitant to rely on hardcoded file-paths.

**Comment by yuriybabenko** [comment]
@nateswart - the issue you found was fixed in #21.

**Comment by geerlingguy** [comment]
@yuriybabenko - `list` should work okay.
