### ISSUE TITLE
Simplify: remove ansible requirement

### ISSUE THREAD

**Issue by nateswart** [LunchboxDevTools/lunchbox#19]
Ansible (on the host) is not actually required for DrupalVM; if it doesn't exist on the host, it is installed in the guest OS and operated from there.

This weekend while testing on a slower machine I was getting some ansible timeout issues. Removing ansible resolved these issues. 

Considering it is one additional requirement/complication let's remove it from the requirements check and not force that it is present. Advanced users always have the option of installing and configuring it manually.

**Comment by geerlingguy** [comment]
:+1:

**Comment by yuriybabenko** [comment]
This requirement is removed in the latest PR.
