### ISSUE TITLE
Vagrant plugins dependency check falsely reports

### ISSUE THREAD

**Issue by nateswart** [LunchboxDevTools/lunchbox#21]
If the required vagrant plugin(s) are missing, dependency check detects there is an issue but still reports that the plugin was found, just that the version is unknown:

`Plugin was found, but the version could not be determined.`

**Comment by yuriybabenko** [comment]
Fixed in https://github.com/LunchboxDevTools/lunchbox/commit/a1c177db016f3aca062ca79179c65390ba6dd8f6.
