### ISSUE TITLE
Sporadic missing data in settings object

### ISSUE THREAD

**Issue by yuriybabenko** [LunchboxDevTools/lunchbox#22]
This error (see screenshot) occasionally occurs on the Settings view. I have seen it occur several times, but am not sure how to reproduce it. It seems that the `window.lunchbox.settings.vm.config` object gets lost at some point, which causes the Settings view to not show the appropriate data (from the `config` object). 

![error](https://cloud.githubusercontent.com/assets/237335/12214447/118552e4-b649-11e5-88fa-64bb8e752906.png)

**Comment by nateswart** [comment]
I just saw this error after using the `Reset` button the settings page.

**Comment by yuriybabenko** [comment]
Thanks, @nateswart. I've seen it happen after the same action, but not always. I suspect a possible race condition.

**Comment by yuriybabenko** [comment]
I believe I fixed this in 9e81f8a30f8b93ee6e8781553a526f94cd65f34f.
